-- MySQL Script generated by MySQL Workbench
-- Sun Nov 28 01:54:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdtienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdtienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdtienda` DEFAULT CHARACTER SET utf8 ;
USE `bdtienda` ;

-- -----------------------------------------------------
-- Table `bdtienda`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`tipo` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `des_tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `usuario` CHAR(10) NULL DEFAULT NULL,
  `clave` CHAR(10) NULL DEFAULT NULL,
  `fecha_registro` DATE NULL DEFAULT NULL,
  `fecha_eliminacion` DATE NULL DEFAULT NULL,
  `idtipo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `idtipo_idx` (`idtipo` ASC) VISIBLE,
  CONSTRAINT `fk_idTipo_tipo`
    FOREIGN KEY (`idtipo`)
    REFERENCES `bdtienda`.`tipo` (`idtipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`caja` (
  `idCaja` INT NOT NULL AUTO_INCREMENT,
  `Des_caja` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCaja`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `dni` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`cab_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`cab_venta` (
  `num_bol` CHAR(5) NOT NULL,
  `fecha_bol` DATETIME NULL DEFAULT NULL,
  `idCliente` INT NOT NULL,
  `idCaja` INT NOT NULL,
  `total_bol` DECIMAL(8,2) NULL DEFAULT NULL,
  `idUsuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`num_bol`),
  INDEX `fk_Venta_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Venta_Caja1_idx` (`idCaja` ASC) VISIBLE,
  INDEX `fk_Usuario_id_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_id`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdtienda`.`usuario` (`idUsuario`),
  CONSTRAINT `fk_Venta_Caja`
    FOREIGN KEY (`idCaja`)
    REFERENCES `bdtienda`.`caja` (`idCaja`),
  CONSTRAINT `fk_Venta_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bdtienda`.`cliente` (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`caja_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`caja_estado` (
  `cod_estado` INT NOT NULL AUTO_INCREMENT,
  `des_estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_estado`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`caja_apertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`caja_apertura` (
  `monto` DECIMAL(8,2) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `comentario` VARCHAR(45) NULL DEFAULT NULL,
  `idCaja` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `cod_estado` INT NOT NULL,
  INDEX `idCaja` (`idCaja` ASC) VISIBLE,
  INDEX `id_usuario_fk_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_cod_estado_idx` (`cod_estado` ASC) VISIBLE,
  CONSTRAINT `caja_apertura_ibfk_1`
    FOREIGN KEY (`idCaja`)
    REFERENCES `bdtienda`.`caja` (`idCaja`),
  CONSTRAINT `fk_cod_estado`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `bdtienda`.`caja_estado` (`cod_estado`),
  CONSTRAINT `id_usuario_fk`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdtienda`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`caja_cierre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`caja_cierre` (
  `monto` DECIMAL(8,2) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `comentario` VARCHAR(45) NULL DEFAULT NULL,
  `idCaja` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `cod_estado` INT NOT NULL,
  INDEX `idCaja` (`idCaja` ASC) VISIBLE,
  INDEX `id_usuario_fk1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_codCierre_estado_idx` (`cod_estado` ASC) VISIBLE,
  CONSTRAINT `caja_cierre_ibfk_1`
    FOREIGN KEY (`idCaja`)
    REFERENCES `bdtienda`.`caja` (`idCaja`),
  CONSTRAINT `fk_codCierre_estado`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `bdtienda`.`caja_estado` (`cod_estado`),
  CONSTRAINT `id_usuario_fk1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdtienda`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `des_categoria` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `ruc` VARCHAR(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `informacion` VARCHAR(45) NULL DEFAULT NULL,
  `Contacto` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `idCategoria` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Categoria1_idx` (`idCategoria` ASC) INVISIBLE,
  INDEX `fk_Producto_idProveedor_idx` (`idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bdtienda`.`categoria` (`idCategoria`),
  CONSTRAINT `fk_Producto_idProveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `bdtienda`.`proveedor` (`idProveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtienda`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtienda`.`detalle_venta` (
  `precio` DECIMAL(8,2) NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `idProducto` INT NOT NULL,
  `num_bol` CHAR(5) NOT NULL,
  INDEX `fk_detalle_venta_producto1_idx` (`idProducto` ASC) VISIBLE,
  INDEX `fk_detalle_venta_cab_venta1_idx` (`num_bol` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_venta_cab_venta1`
    FOREIGN KEY (`num_bol`)
    REFERENCES `bdtienda`.`cab_venta` (`num_bol`),
  CONSTRAINT `fk_detalle_venta_producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdtienda`.`producto` (`idProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `bdtienda` ;

-- -----------------------------------------------------
-- procedure consultarId
-- -----------------------------------------------------

DELIMITER $$
USE `bdtienda`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `consultarId`(id int)
BEGIN
select * from bdtienda.usuario where idUsuario = id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_des_tipo
-- -----------------------------------------------------

DELIMITER $$
USE `bdtienda`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_des_tipo`(xid int)
BEGIN
select u.*,t.des_tipo from bdtienda.usuario u inner join bdtienda.tipo t 
on u.idtipo = t.idtipo
where u.idusuario = xid;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_listarTipo
-- -----------------------------------------------------

DELIMITER $$
USE `bdtienda`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_listarTipo`()
BEGIN
select u.*,t.des_tipo from bdtienda.usuario u inner join bdtienda.tipo t 
on u.idtipo = t.idtipo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_listar_Producto
-- -----------------------------------------------------

DELIMITER $$
USE `bdtienda`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_listar_Producto`(idPro int)
BEGIN
select p.idProducto,p.nombre,p.cantidad,p.precio,c.des_categoria,pro.nombre from bdtienda.producto p inner join bdtienda.categoria c on p.idCategoria = c.idCategoria
								  inner join bdtienda.proveedor pro on p.idProveedor = pro.idProveedor 
where p.idProducto = idPro;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_listar_proCat
-- -----------------------------------------------------

DELIMITER $$
USE `bdtienda`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_listar_proCat`(idCat int)
BEGIN
 select p.idProducto,p.nombre,p.cantidad,p.precio,c.des_categoria from bdtienda.producto p inner join bdtienda.categoria c
 on p.idCategoria = c.idCategoria
 Where p.idCategoria = idCat;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_listarpro
-- -----------------------------------------------------

DELIMITER $$
USE `bdtienda`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_listarpro`()
BEGIN
select p.idProducto,p.nombre,p.cantidad,p.precio,c.des_categoria,pro.nombre from bdtienda.producto p inner join bdtienda.categoria c on p.idCategoria = c.idCategoria
								  inner join bdtienda.proveedor pro on p.idProveedor = pro.idProveedor ;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_validar
-- -----------------------------------------------------

DELIMITER $$
USE `bdtienda`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_validar`(usr char(10), psw char(10))
BEGIN
select * from bdtienda.usuario 
where usuario = usr and clave = psw ;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
